### ISSUE TITLE
Allow ability to use noted bones on "Virilis" NPC in Varlamore

### ISSUE THREAD

**Issue by fishaxe** [mad-s/easy-unnote#9]
NPC called "Virilis" (https://oldschool.runescape.wiki/w/Virilis) can un-note bones for players at the Exposed Altar, would it be possible to allow notes to be used on him as I have to turn the plugin off to be able to use him? Thank you

P.S New to GitHub so unsure if I have posted this suggestion in the right place. Thank you :)

**Comment by Syphontwo** [comment]
I'll submit an update for this.  Easy change.  Not sure if the original maintainer will accept it though.

**Comment by mad-s** [comment]
Closed in #10. I'll look into the other issues and try to push another release in the next few days
